### ISSUE TITLE
Errors when running rake db:seed

### ISSUE THREAD

**Issue by heathermiller114** [learn-co-curriculum/namespaced-routes-lab#28]
After opening the lab and running ``` rake db:seed ``` i got the following errors: 
```
rake aborted!
LoadError: cannot load such file -- active_storage/engine
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:80:in `register'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:36:in `rescue in require'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:25:in `require'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/config/application.rb:8:in `<top (required)>'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/Rakefile:4:in `require'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/Rakefile:4:in `<top (required)>'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>' 
```
So I tried commenting out ``` #require 'active_storage/engine' ``` in config/application.rb but then I get the error: 
```
rake aborted!
NoMethodError: undefined method `load_defaults' for #<Rails::Application::Configuration:0x00007fb26ed473f8>
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.1/lib/rails/railtie/configuration.rb:95:in `method_missing'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/config/application.rb:23:in `<class:Application>'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/config/application.rb:21:in `<module:DisplayingAssociationsRailsLab>'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/config/application.rb:20:in `<top (required)>'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/Rakefile:4:in `require'
/Users/heathermiller/flatiron/namespaced-routes-lab-v-000/Rakefile:4:in `<top (required)>'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/heathermiller/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace
```
After this, every google rabbit hole I start going down just leads me to more errors

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials based on #26 and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
